/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DelegationRouteImport } from './routes/delegation'
import { Route as ProposalProposalIdRouteImport } from './routes/proposal.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegationRoute = DelegationRouteImport.update({
  id: '/delegation',
  path: '/delegation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalProposalIdRoute = ProposalProposalIdRouteImport.update({
  id: '/proposal/$proposalId',
  path: '/proposal/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/delegation' | '/proposal/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delegation' | '/proposal/$proposalId'
  id: '__root__' | '/' | '/delegation' | '/proposal/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelegationRoute: typeof DelegationRoute
  ProposalProposalIdRoute: typeof ProposalProposalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegation': {
      id: '/delegation'
      path: '/delegation'
      fullPath: '/delegation'
      preLoaderRoute: typeof DelegationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$proposalId': {
      id: '/proposal/$proposalId'
      path: '/proposal/$proposalId'
      fullPath: '/proposal/$proposalId'
      preLoaderRoute: typeof ProposalProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelegationRoute: DelegationRoute,
  ProposalProposalIdRoute: ProposalProposalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
