/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DelegationRouteImport } from './routes/delegation'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationsUnsubscribeRouteImport } from './routes/notifications.unsubscribe'
import { Route as ProposalProposalIdRouteImport } from './routes/proposal.$proposalId'
import { Route as ApiCronNotificationsRouteImport } from './routes/api/cron.notifications'
import { Route as ApiNotificationsTelegramRouteImport } from './routes/api/notifications.telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegationRoute = DelegationRouteImport.update({
  id: '/delegation',
  path: '/delegation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsUnsubscribeRoute = NotificationsUnsubscribeRouteImport.update({
  id: '/notifications/unsubscribe',
  path: '/notifications/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalProposalIdRoute = ProposalProposalIdRouteImport.update({
  id: '/proposal/$proposalId',
  path: '/proposal/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNotificationsRoute = ApiCronNotificationsRouteImport.update({
  id: '/api/cron/notifications',
  path: '/api/cron/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsTelegramRoute = ApiNotificationsTelegramRouteImport.update({
  id: '/api/notifications/telegram',
  path: '/api/notifications/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/notifications': typeof NotificationsRoute
  '/notifications/unsubscribe': typeof NotificationsUnsubscribeRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/notifications/telegram': typeof ApiNotificationsTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/notifications': typeof NotificationsRoute
  '/notifications/unsubscribe': typeof NotificationsUnsubscribeRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/notifications/telegram': typeof ApiNotificationsTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delegation': typeof DelegationRoute
  '/notifications': typeof NotificationsRoute
  '/notifications/unsubscribe': typeof NotificationsUnsubscribeRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/notifications/telegram': typeof ApiNotificationsTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delegation'
    | '/notifications'
    | '/notifications/unsubscribe'
    | '/proposal/$proposalId'
    | '/api/cron/notifications'
    | '/api/notifications/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delegation'
    | '/notifications'
    | '/notifications/unsubscribe'
    | '/proposal/$proposalId'
    | '/api/cron/notifications'
    | '/api/notifications/telegram'
  id:
    | '__root__'
    | '/'
    | '/delegation'
    | '/notifications'
    | '/notifications/unsubscribe'
    | '/proposal/$proposalId'
    | '/api/cron/notifications'
    | '/api/notifications/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelegationRoute: typeof DelegationRoute
  NotificationsRoute: typeof NotificationsRoute
  NotificationsUnsubscribeRoute: typeof NotificationsUnsubscribeRoute
  ProposalProposalIdRoute: typeof ProposalProposalIdRoute
  ApiCronNotificationsRoute: typeof ApiCronNotificationsRoute
  ApiNotificationsTelegramRoute: typeof ApiNotificationsTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegation': {
      id: '/delegation'
      path: '/delegation'
      fullPath: '/delegation'
      preLoaderRoute: typeof DelegationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/unsubscribe': {
      id: '/notifications/unsubscribe'
      path: '/notifications/unsubscribe'
      fullPath: '/notifications/unsubscribe'
      preLoaderRoute: typeof NotificationsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$proposalId': {
      id: '/proposal/$proposalId'
      path: '/proposal/$proposalId'
      fullPath: '/proposal/$proposalId'
      preLoaderRoute: typeof ProposalProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notifications': {
      id: '/api/cron/notifications'
      path: '/api/cron/notifications'
      fullPath: '/api/cron/notifications'
      preLoaderRoute: typeof ApiCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/telegram': {
      id: '/api/notifications/telegram'
      path: '/api/notifications/telegram'
      fullPath: '/api/notifications/telegram'
      preLoaderRoute: typeof ApiNotificationsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelegationRoute: DelegationRoute,
  NotificationsRoute: NotificationsRoute,
  NotificationsUnsubscribeRoute: NotificationsUnsubscribeRoute,
  ProposalProposalIdRoute: ProposalProposalIdRoute,
  ApiCronNotificationsRoute: ApiCronNotificationsRoute,
  ApiNotificationsTelegramRoute: ApiNotificationsTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
